[WIP] Replace & update metadata on `copy`
conda-forge/conda-forge-webservices pull request #559
Opened 2023-06-13 21:37 UTC by jakirkham

When copying over a package from [the staging channel, `cf-staging`]( https://anaconda.org/cf-staging ), to [the main channel, `conda-forge`]( https://anaconda.org/conda-forge ), make sure to refresh all associated metadata as part of the copy.

<hr>

Checklist
* [ ] Pushed the branch to main repo
* [ ] CI passed on the branch

<hr>

xref: https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/241
xref: https://github.com/conda/infrastructure/discussions/649#discussioncomment-6167410

2023-06-13 21:42 UTC, jakirkham commented
cc @beckermr

2023-06-13 21:48 UTC, leofang commented
LGTM, thx John for speedy patch

2023-06-13 22:22 UTC, beckermr commented on conda_forge_webservices/feedstock_outputs.py
> +                    replace=True,
Where are the docs on this?

2023-06-13 22:27 UTC, beckermr requested changes
We need to know exactly what this does.

2023-06-13 22:27 UTC, beckermr commented on conda_forge_webservices/feedstock_outputs.py
> +                    replace=True,
This will overwrite files too. Normally we don't get duplicate uploads, but if we happen to, we'd nuke our own files. That is too dangerous to use in production

2023-06-13 22:27 UTC, beckermr commented on conda_forge_webservices/feedstock_outputs.py
> +                    replace=True,
https://github.com/Anaconda-Platform/anaconda-client/blob/master/binstar_client/mixins/package.py#L35

2023-06-13 22:33 UTC, jakirkham commented on conda_forge_webservices/feedstock_outputs.py
> +                    replace=True,
It's visible via the CLI. Also here's [the source code]( https://github.com/Anaconda-Platform/anaconda-client/blob/662968b37fa61018a3e8524dc3ea5084e9aa4037/binstar_client/mixins/package.py#L15-L16 )

That said, not sure what counts as docs for `anaconda-client`. The [GitHub project's README links]( https://github.com/Anaconda-Platform/anaconda-client#quickstart ) to [this page]( https://docs.anaconda.org/free/anacondaorg/ ), which [also shows the CLI]( https://docs.anaconda.org/free/anacondaorg/commandreference#copy ), but not much more

<details>

<summary><code>anaconda copy --help</code></summary>

```bash
usage: anaconda copy [-h] [--to-owner TO_OWNER] [--from-label FROM_LABEL]
                     [--to-label TO_LABEL] [--replace | --update]
                     spec

Copy packages from one account to another

positional arguments:
  spec                  Package - written as user/package/version[/filename]
                        If filename is not given, copy all files in the
                        version

options:
  -h, --help            show this help message and exit
  --to-owner TO_OWNER   User account to copy package to (default: your
                        account)
  --from-label FROM_LABEL
                        Label to copy packages from
  --to-label TO_LABEL   Label to put all packages into
  --replace             Overwrite destination package metadata
  --update              Update missing data in destination package metadata
```

</details>

2023-06-13 22:36 UTC, jakirkham commented
Hey Matt, it seems like a bunch of comments just came through

In any event, wrote up an answer above ( https://github.com/conda-forge/conda-forge-webservices/pull/559#discussion_r1228767788 )

Just pointing it out here so it is hopefully easier to find 🙂

2023-06-13 22:39 UTC, beckermr commented
Thanks! Maybe it should be tested on a test channel to make sure?

2023-06-13 22:39 UTC, jakirkham commented on conda_forge_webservices/feedstock_outputs.py
> +                    replace=True,
We could use `update` if we prefer to keep the existing metadata

Went with `replace` as I was concerned old metadata would hang around (like dead links, outdated descriptions, etc.)

```suggestion
                    update=True,
```

2023-06-13 22:47 UTC, jakirkham commented
> Maybe it should be tested on a test channel to make sure?

@leofang, is this something you would be comfortable exploring? 🙂

IIUC we would need to

1. Create 2 channels
2. Create a package without a `license_url` field
3. Upload that package (`anaconda upload ...`)
4. Try copying it to the second (`anaconda copy ...`)
5. Validate the `license_url` is missing
6. Repeat 2 with a build number bump and a `license_url` field specified
7. Repeat 3 with the new package build
8. Repeat 4 with the new package build
9. Repeat 5 now with a working `license_url`

@beckermr please feel free to edit the steps in this comment directly 🙂

2023-06-13 22:56 UTC, beckermr commented on conda_forge_webservices/feedstock_outputs.py
> +                    replace=True,
I'm worried about overwriting the actual package contents. I cannot tell from the api client source and docs if these flags are just for metadata or are for the package itself too.

2023-06-13 22:57 UTC, beckermr commented
We should also see what a duplicate upload does.

2023-06-13 23:26 UTC, jakirkham commented on conda_forge_webservices/feedstock_outputs.py
> +                    replace=True,
That sounds like a reasonable concern

Would be happy to try with `update` first and follow up on `replace` separately

What do you think?

2023-06-13 23:27 UTC, jakirkham commented
Could you please elaborate on how that would factor in? Which step(s) would be relevant?

For example do we sometimes upload duplicate packages to `cf-staging`? Or do we sometimes copy packages over to `conda-forge` that when they are already on `conda-forge`? Or something else?

2023-06-13 23:46 UTC, beckermr commented on conda_forge_webservices/feedstock_outputs.py
> +                    replace=True,
yes i'd be happy to ship update now and punt on replace until we do more testing.

2023-06-13 23:46 UTC, beckermr commented on conda_forge_webservices/feedstock_outputs.py
> +                    replace=True,
We may also hear back from anaconda on what these do.

2023-06-13 23:47 UTC, beckermr commented
Right. We have a ton of internal checks for duplicate uploads, but our system is not "air tight" so to speak and can be subject to race conditions. I'm worried about packages with the same name but different metadata.

2023-06-14 00:18 UTC, beckermr commented
Yeah replace is not safe. See this simple test

```
(cf-dev) macbook-air:test_upload beckermr$ anaconda copy conda-forge/scaleapi/2.14.4/noarch/scaleapi-2.14.4-pyhd8ed1ab_0.conda
Using Anaconda API: https://api.anaconda.org
Copied file: noarch/scaleapi-2.14.4-pyhd8ed1ab_0.conda
Copied 1 files! 
(cf-dev) macbook-air:test_upload beckermr$ anaconda copy conda-forge/scaleapi/2.14.4/noarch/scaleapi-2.14.4-pyhd8ed1ab_0.conda
Using Anaconda API: https://api.anaconda.org
[ERROR] File conflict while copying! Try to use --replace or --update options for force copying
(cf-dev) macbook-air:test_upload beckermr$ anaconda copy conda-forge/scaleapi/2.14.4/noarch/scaleapi-2.14.4-pyhd8ed1ab_0.conda --replace
Using Anaconda API: https://api.anaconda.org
Copied file: noarch/scaleapi-2.14.4-pyhd8ed1ab_0.conda
Copied 1 files! 
(cf-dev) macbook-air:test_upload beckermr$ anaconda copy conda-forge/scaleapi/2.14.4/noarch/scaleapi-2.14.4-pyhd8ed1ab_0.conda --update
Using Anaconda API: https://api.anaconda.org
Copied 0 files! 
NOTE: copy command with --update option doesn`t copy already existing files. Try to use --replace to overwrite existing data
```

`--replace` will overwrite the package in addition to the metadata.

2023-06-14 00:19 UTC, beckermr commented
Update will fill missing fields but not overwrite existing ones.

2023-06-14 00:33 UTC, jakirkham commented on conda_forge_webservices/feedstock_outputs.py
> +                    replace=True,
Sounds like we want `update` ( https://github.com/conda-forge/conda-forge-webservices/pull/559#issuecomment-1590241850 ). Will make this change

2023-06-14 00:39 UTC, jakirkham commented
Thanks Matt! 🙏

Sounds like `update` is the way to go. Have switched to that

We may want to revisit metadata going stale relative to new package uploads, but that would need to be a new issue (likely requiring `anaconda-client` and `anaconda.org` changes) given the observations above

2023-06-14 00:40 UTC, beckermr commented
Ok. The last step here is to push this to a branch on the upstream repo for testing.

2023-06-14 00:44 UTC, jakirkham commented
Have done that already (this PR is based on upstream branch). However I forgot the first time ( https://github.com/conda-forge/conda-forge-webservices/pull/558 ) 🤦‍♂️

Though there was a legitimate test failure. Think the last commit fixes

2023-06-14 00:59 UTC, jakirkham commented
Looks green 🟢

2023-06-14 01:04 UTC, merged

2023-06-14 01:12 UTC, jakirkham commented
Thanks Matt! 🙏

@leofang, would you like to give this another try? 🙂

2023-06-17 01:07 UTC, leofang commented
Thanks guys, sorry it's been a crazy week. I rebuilt our packages and it seems `update` does fix the issue, the license appears now. I'll follow up in the infra thread.
<img width="600" alt="截圖 2023-06-16 下午9 06 59" src="https://github.com/conda-forge/conda-forge-webservices/assets/5534781/3375ad85-9b10-474d-8d16-27d9aaeab77f">

2023-06-17 01:14 UTC, beckermr commented
Was that field empty before?

2023-06-17 01:15 UTC, leofang commented
Yes: https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/241#issuecomment-1589517475