move to pyproject.toml, enable ruff-format and mypy
conda-forge/conda-forge-webservices pull request #639
Opened 2024-07-22 06:20 UTC by wolfv

I removed a few try-imports (for py2 - 3 transition, presumably).

I enabled mypy and made it pass. 

I activated `ruff-format`. 

I moved from `setup.py` to `pyproject.toml` (someone should check that it didn't change anything).

Should we change the authors of this project?

2024-07-22 06:21 UTC, wolfv commented on conda_forge_webservices/commands.py
> +            I just wanted to let you know that I updated the team with maintainers from {default_branch}.
changed to use a f-string.

2024-07-22 06:23 UTC, wolfv commented on conda_forge_webservices/tests/test_webapp.py
> +from urllib.parse import urlencode
removed try import to make mypy complain less.

2024-07-22 10:36 UTC, beckermr requested changes
This pr is way to big. Let's do each thing one at a time in separate prs please.

2024-07-24 07:46 UTC, wolfv commented
Superseded by a number of other PRs :)

2024-07-24 07:46 UTC, closed without merging